### ISSUE TITLE
getInstance crashes

### ISSUE THREAD

**Issue by Raptorhugo** [developermypos/myPOS-SDK-Android#1]
Hi , I'm going to integrate SDK on my Application. 
I followed step by step documentation  to do that.

Your Demo works, but not mine:
**`PosHandler.getInstance() `**
generate NullPointReferenceException at line 144 of PosHandler.class.
I saw that  SDKApplication.getAppContext() is equals null.

Any idea ?
regards

**Comment by YiffyToys** [comment]
no response since 2018?
