### ISSUE TITLE
Exception on target 31 and above

### ISSUE THREAD

**Issue by EinarArnason** [developermypos/myPOS-SDK-Android#17]
I get this exception when targeting 31 (Android 12)

`E/AndroidRuntime(14064): FATAL EXCEPTION: Thread-4
E/AndroidRuntime(14064): Process: com.systemat.travelboy_interface, PID: 14064
E/AndroidRuntime(14064): java.lang.IllegalArgumentException: com.systemat.travelboy_interface: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(14064): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(14064): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(14064): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime(14064): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime(14064): 	at h0.f.p(Unknown Source:55)
E/AndroidRuntime(14064): 	at h0.f.b(Unknown Source:15)
E/AndroidRuntime(14064): 	at com.mypos.slavesdk.b0$a.run(Unknown Source:167)
E/AndroidRuntime(14064): 	at java.lang.Thread.run(Thread.java:920)
`

**Comment by StiliyanKovachev** [comment]
Please try 'com.mypos:slavesdk:2.1.0'
