### ISSUE TITLE
Make connect dialog optional

### ISSUE THREAD

**Issue by rbedemann** [developermypos/myPOS-SDK-Android#19]
Hi,

when calling the connect method to connect a bluetooth device, there's always a dialog being shown. Would it be possible to make this optional? Especially when using `public void connectDevice(Context context, String deviceSN)` it doesn't really make sense, as the device to connect with is already specified via Serial number. 

In our case it would probably confuse the user, as the dialog is not properly integrated in the entire UX and also in a different language.

Thanks in advance!

**Comment by StiliyanKovachev** [comment]
Hi,

in the new version you can pass BluetoothDevice as parameter to `public void connectDevice(Context context, BluetoothDevice bluetoothDevice)` method. It will be available soon

**Comment by rbedemann** [comment]
Great news! Thanks for the update!

**Comment by StiliyanKovachev** [comment]
version 'com.mypos:slavesdk:2.1.1' is live now. Please update

**Comment by rbedemann** [comment]
Thanks for releasing the new version! Unfortunately I still see the old method signature...


![Screenshot 2022-09-30 at 11 56 12](https://user-images.githubusercontent.com/3638491/193245371-47b42949-a6f9-4c18-98e2-b259bee33a6c.png)

**Comment by StiliyanKovachev** [comment]
Sorry, something went wrong with the publishing. I released a new version 2.1.2. it will be available up to several days

**Comment by StiliyanKovachev** [comment]
it is live now
