### ISSUE TITLE
ERROR:/Users/mac/Desktop/ReactNative/paymentmachine/android/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml:1619: AAPT: error: style attribute 'attr/layout_rowWeight (aka com.paymentmachine:attr/layout_rowWeight)' not found.

### ISSUE THREAD

**Issue by ahmad71666** [developermypos/myPOS-SDK-Android#20]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

**Comment by StiliyanKovachev** [comment]
Hi,

add this to your build.gradle dependencies

 implementation 'androidx.gridlayout:gridlayout:1.0.0'
