### ISSUE TITLE
Can we connect with terminal using socket connection through wifi?

### ISSUE THREAD

**Issue by ahmad71666** [developermypos/myPOS-SDK-Android#22]

**Comment by StiliyanKovachev** [comment]
Hi,

There isn't direct way to connect terminal via TCP/IP socket using IPProtocol.

This is our [Cash Register Remote API](https://developers.mypos.com/en/doc/in_person_payments/v1_0/356-cash-register-remote-api) . It can be used to send payments to terminal over the network.

Best regards
