### ISSUE TITLE
Trasaction decline

### ISSUE THREAD

**Issue by merlin100** [developermypos/myPOS-SDK-Android#23]
During integration with mini Go2 demo device and test transaction get always response  0. 
Demo.mypos.eu say for transaction - Decline. The recipe says response code 96 - System error Decline.
What is wrong?

**Comment by StiliyanKovachev** [comment]
Hi,

Please forward your request to [online@mypos.com](mailto:online@mypos.com) . myPOS dev support will proceed your issue.

Thanks

**Comment by merlin100** [comment]
Hi,

thanks, support fixed that problem.
