### ISSUE TITLE
Payment via direct SDK method

### ISSUE THREAD

**Issue by merlin100** [developermypos/myPOS-SDK-Android#24]
Hi,

If payment via direct SDK method is used, how can I know that the transaction has been canceled?

Best regards
Aliaksandr

**Comment by StiliyanKovachev** [comment]
Hi,

Before starting the transaction you have to set pos info listener

POSHandler.getInstance().setPOSInfoListener(new POSInfoListener() {

            @Override
            public void onPOSInfoReceived(final int command, final int status, final String description, Bundle extra) {
            ....

Here is a list with all pos statuses that means transaction uninterrupted:
 
POSHandler.POS_STATUS_NO_CARD_FOUND
POSHandler.POS_STATUS_WRONG_AMOUNT
POSHandler.POS_STATUS_INTERNAL_ERROR
POSHandler.POS_STATUS_CARD_CHIP_ERROR
POSHandler.POS_STATUS_TERMINAL_BUSY
POSHandler.POS_STATUS_USER_CANCEL
POSHandler.POS_STATUS_ACTIVATION_REQUIRED
POSHandler.POS_STATUS_MANDATORY_UPDATE
POSHandler.POS_STATUS_UNSUPPORTED_SDK_VERSION
POSHandler.POS_STATUS_MAX_PIN_COUNT_EXCEEDED
POSHandler.POS_STATUS_INVALID_OR_MISSING_PREAUTH_CODE
POSHandler.POS_STATUS_PREAUTH_TRAN_BEEN_COMPLETED
POSHandler.POS_STATUS_INVALID_PREAUTH_AMOUNT
POSHandler.POS_STATUS_TRANSACTION_FORBIDDEN
POSHandler.POS_STATUS_WRONG_TIPPING_AMOUNT
POSHandler.POS_STATUS_WRONG_PASSWORD
POSHandler.POS_STATUS_INVALID_OPERATOR_CODE
POSHandler.POS_STATUS_INVALID_REFERENCE_NUMBER_TYPE
POSHandler.POS_STATUS_INVALID_REFERENCE_NUMBER
POSHandler.POS_STATUS_PAYMENT_INVALID_REQUEST_CODE
POSHandler.POS_STATUS_COM_ERROR

**Comment by merlin100** [comment]
Hi,

thank you very mach.
Is correct POSHandler.POS_STATUS_PREAUTH_TRAN_BEEN_COMPLETED in that list?
Are missing?
   POS_STATUS_INVALID_PAN
   POS_STATUS_INVALID_EXP_DATE

**Comment by StiliyanKovachev** [comment]
Those statuses

POS_STATUS_INVALID_PAN
POS_STATUS_INVALID_EXP_DATE

are related if you doing MO/TO transactions.

Preauth - related to pre-authorizations

**Comment by merlin100** [comment]
ok thanks

**Comment by merlin100** [comment]
It's clear
