### ISSUE TITLE
Last transaction not completed yet

### ISSUE THREAD

**Issue by philsnook** [developermypos/myPOS-SDK-Android#3]
How can we programmatically clear the previous transaction? I get the message 'Last transaction not completed yet' when calling: 
```
         mPOSHandler.openPaymentActivity(
                        pos.this /*activity*/,
                        REQUEST_CODE_MAKE_PAYMENT /*requestCode*/,
                        "10.50" /*amount*/,
                        UUID.randomUUID().toString()/*transaction reference*/
                );
```

A reboot of the device does not seem to solve the issue.
![screenshot-1555231006352](https://user-images.githubusercontent.com/19917994/56090322-d69a7f00-5e98-11e9-98a2-aaceec372c2b.jpg)
 
![screenshot-1555231330002](https://user-images.githubusercontent.com/19917994/56090391-aef7e680-5e99-11e9-9de8-3b7872bdf7f2.jpg)

**Comment by philsnook** [comment]
The problem was caused by this event being fired twice..

I have now resolved the issue.

```
       mPOSHandler.setConnectionListener(new ConnectionListener() {
            @Override
            public void onConnected(final BluetoothDevice device) {

``

**Comment by AndreTaxiDigital** [comment]
I checked my code I the setConnectionListener is just called once but I always receive "Last transaction not completed yet". Any help?
